development:
  adapter: postgresql
  database: flappy
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: flappy
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: flappy
  pool: 5
  timeout: 5000

